-- Calibre beta community layer. Run this once in Supabase SQL Editor.
create table if not exists public.debates (
  slug text primary key,
  title text not null,
  category text not null default 'rate-battle',
  votes integer not null default 0,
  comments integer not null default 0,
  left_player text,
  right_player text,
  published boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.hot_potatoes (
  slug text primary key,
  title text not null,
  context text,
  yes integer not null default 50,
  published boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.banger_tweets (
  id bigint generated by default as identity primary key,
  handle text not null,
  text text not null,
  likes text default '0',
  reposts text default '0',
  published boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.debate_nominations (
  id bigint generated by default as identity primary key,
  title text not null,
  reason text not null,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  created_at timestamptz not null default now()
);
create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  thread_slug text not null,
  body text not null,
  user_id uuid references auth.users(id) on delete cascade,
  author_email text,
  created_at timestamptz not null default now()
);
create table if not exists public.goat_votes (
  id bigint generated by default as identity primary key,
  choice text not null check (choice in ('Messi','Ronaldo')),
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id)
);

alter table public.debates enable row level security;
alter table public.hot_potatoes enable row level security;
alter table public.banger_tweets enable row level security;
alter table public.debate_nominations enable row level security;
alter table public.forum_posts enable row level security;
alter table public.goat_votes enable row level security;

create policy "public reads published debates" on public.debates for select using (published = true);
create policy "public reads hot potatoes" on public.hot_potatoes for select using (published = true);
create policy "public reads banger tweets" on public.banger_tweets for select using (published = true);
create policy "signed users nominate debates" on public.debate_nominations for insert to authenticated with check (auth.uid() = user_id);
create policy "public reads forum posts" on public.forum_posts for select using (true);
create policy "signed users write forum posts" on public.forum_posts for insert to authenticated with check (auth.uid() = user_id);
create policy "signed users cast goat vote" on public.goat_votes for insert to authenticated with check (auth.uid() = user_id);

insert into public.debates(slug,title,category,votes,comments,left_player,right_player) values
('pedri-vs-jude','Pedri vs Bellingham: who owns the midfield?','rate-battle',15100,384,'Pedri','Jude Bellingham'),
('arsenal-control-vs-chaos','Would Arsenal be better with control or chaos?','hot-potato',8421,205,null,null),
('mbappe-vs-haaland','Mbappé vs Haaland: who changes a game faster?','rate-battle',24700,511,'Kylian Mbappé','Erling Haaland'),
('vini-vs-saka','Vinícius vs Saka: who breaks the structure first?','rate-battle',12200,176,'Vinícius Júnior','Bukayo Saka')
on conflict (slug) do nothing;

insert into public.hot_potatoes(slug,title,context,yes) values
('arsenal-control-vs-chaos','Would Arsenal be better with control or chaos?','One profile protects the structure. The other makes the game harder to control.',52),
('ter-stegen-finished','Is ter Stegen truly finished at the top level?','Reputation, injuries and the eye test are pulling in different directions.',43),
('women-equal-pay','Should women players receive equal international-match pay?','A football argument with sporting, commercial and institutional layers.',66)
on conflict (slug) do nothing;

insert into public.banger_tweets(handle,text,likes,reposts) values
('@CalibreFooty','Goals tell you who finished the move. They do not always tell you who made the game possible.','4.8K','1.1K'),
('@CarlyTalksBall','The midfielder who keeps the structure alive will always lose the clip war to the player arriving in the box.','3.6K','782');
