/**
 * statsBombService.js
 * Calibre – StatsBomb Open Data Integration
 * ─────────────────────────────────────────────────────────────────
 * Serves pre-computed tournament player stats from the StatsBomb
 * open data repo (free, CC-BY-SA 4.0 licensed).
 *
 * Static JSON files live in /public/data/statsbomb/
 * Generated by: scripts/generateStatsBombData.mjs
 *
 * Usage:
 *   import { getTournamentStats, searchPlayerTournaments } from '../services/statsBombService';
 */

const BASE_URL = '/data/statsbomb';

// Competition registry — mirrors public/data/statsbomb/sb_index.json
export const SB_COMPETITIONS = [
  { id: 'sb_55_282',   name: 'Euro 2024',               competition_id: 55,   season_id: 282, gender: 'male',   has360: true  },
  { id: 'sb_1267_107', name: 'AFCON 2023',               competition_id: 1267, season_id: 107, gender: 'male',   has360: true  },
  { id: 'sb_43_106',   name: 'World Cup 2022',           competition_id: 43,   season_id: 106, gender: 'male',   has360: true  },
  { id: 'sb_72_107',   name: "Women's World Cup 2023",   competition_id: 72,   season_id: 107, gender: 'female', has360: true  },
  { id: 'sb_53_315',   name: "Women's Euro 2025",        competition_id: 53,   season_id: 315, gender: 'female', has360: true  },
  { id: 'sb_223_282',  name: 'Copa America 2024',        competition_id: 223,  season_id: 282, gender: 'male',   has360: false },
  { id: 'sb_9_281',    name: 'Bundesliga 2023/24',       competition_id: 9,    season_id: 281, gender: 'male',   has360: true  },
  { id: 'sb_7_235',    name: 'Ligue 1 2022/23',          competition_id: 7,    season_id: 235, gender: 'male',   has360: true  },
  { id: 'sb_44_107',   name: 'MLS 2023',                 competition_id: 44,   season_id: 107, gender: 'male',   has360: true  },
];

// In-memory cache: { [fileId]: { data, ts } }
const _cache = {};
const CACHE_TTL = 30 * 60 * 1000; // 30 minutes

/**
 * Fetch a competition dataset.
 * Returns the full { competition, players, total_matches, ... } object.
 */
export async function getTournamentStats(fileId) {
  const now = Date.now();
  if (_cache[fileId] && now - _cache[fileId].ts < CACHE_TTL) {
    return _cache[fileId].data;
  }
  const url = `${BASE_URL}/${fileId}.json`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`StatsBomb: failed to load ${fileId} (${res.status})`);
  const data = await res.json();
  _cache[fileId] = { data, ts: now };
  return data;
}

/**
 * Search for a player across all StatsBomb competitions.
 * Matches by name (case-insensitive, partial allowed).
 *
 * Returns: Array of { competition, season, stats }
 */
export async function searchPlayerTournaments(playerName) {
  const query = playerName.toLowerCase().trim();
  const results = [];

  await Promise.all(
    SB_COMPETITIONS.map(async (comp) => {
      try {
        const dataset = await getTournamentStats(comp.id);
        const match = dataset.players.find(p =>
          p.name.toLowerCase().includes(query) ||
          // Handle name variants (Mbappé → mbappe)
          normalise(p.name).includes(normalise(query))
        );
        if (match) {
          results.push({
            comp_id: comp.id,
            competition: comp.name,
            gender: comp.gender,
            has360: comp.has360,
            stats: match,
          });
        }
      } catch (e) {
        // Silently skip missing competition files
      }
    })
  );

  // Sort by most recent / most relevant
  const ORDER = ['Euro 2024', "Women's Euro 2025", 'Copa America 2024', 'AFCON 2023',
                 "Women's World Cup 2023", 'World Cup 2022', 'Bundesliga 2023/24',
                 'Ligue 1 2022/23', 'MLS 2023'];
  results.sort((a, b) => ORDER.indexOf(a.competition) - ORDER.indexOf(b.competition));

  return results;
}

/**
 * Get top performers in a competition for a given metric.
 * metric: 'goals' | 'assists' | 'xg' | 'key_passes' | 'pressures' | 'interceptions'
 * limit: number of results
 */
export async function getLeaderboard(fileId, metric = 'goals', limit = 10) {
  const dataset = await getTournamentStats(fileId);
  return [...dataset.players]
    .sort((a, b) => (b[metric] || 0) - (a[metric] || 0))
    .slice(0, limit);
}

/**
 * Get a narrative summary string for a player's tournament stats.
 * Used in the player profile modal "Tournament" tab.
 */
export function buildTournamentNarrative(stats, competitionName) {
  const parts = [];
  if (stats.goals > 0) parts.push(`${stats.goals} goal${stats.goals !== 1 ? 's' : ''}`);
  if (stats.assists > 0) parts.push(`${stats.assists} assist${stats.assists !== 1 ? 's' : ''}`);
  if (parts.length === 0 && stats.key_passes > 0) parts.push(`${stats.key_passes} key passes`);

  const contribution = parts.length > 0 ? parts.join(' and ') : 'featured throughout the tournament';
  const xgNote = stats.xg > 0 ? ` (xG: ${stats.xg})` : '';
  const efficiency = stats.goals > 0 && stats.xg > 0
    ? stats.goals > stats.xg
      ? ' — clinical finish, over-performed xG'
      : stats.goals < stats.xg * 0.6
      ? ' — underperformed xG'
      : ''
    : '';

  return `${competitionName}: ${contribution}${xgNote}${efficiency}. ${stats.matches} appearance${stats.matches !== 1 ? 's' : ''}, ${stats.pass_accuracy}% pass accuracy.`;
}

// ── Helpers ────────────────────────────────────────────────────────

function normalise(str) {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
}
