import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Crown, Flame, LockKeyhole, MessageSquare, Send, Star, TrendingUp, Users, X, Zap } from 'lucide-react';
import { navigateTo } from '../components/NavLink.jsx';
import ApiPlayerImage from '../components/ApiPlayerImage.jsx';
import { playerIdFor } from '../data/playerIds.js';
import useAuth from '../hooks/useAuth.js';
import { castGoatVote, loadBangerTweets, loadDebateFeed, loadForumPosts, loadHotPotatoes, submitDebateNomination, submitForumPost } from '../services/community.js';

const BATTLE_VISUALS={
  'pedri-vs-jude':['Pedri','Jude Bellingham'], 'mbappe-vs-haaland':['Kylian Mbappé','Erling Haaland'], 'vini-vs-saka':['Vinícius Júnior','Bukayo Saka'],
};
function requestAuth(returnTo='/debates'){window.dispatchEvent(new CustomEvent('calibre:open-auth',{detail:{returnTo}}));}
function ForumModal({slug,title,onClose}){const{user}=useAuth();const[draft,setDraft]=useState('');const[posts,setPosts]=useState([]);const[notice,setNotice]=useState('');useEffect(()=>{loadForumPosts(slug).then(setPosts).catch(()=>setPosts([]));},[slug]);async function post(){if(!user)return requestAuth(`/debates?forum=${slug}`);const body=draft.trim();if(!body)return;try{const saved=await submitForumPost({threadSlug:slug,body,user});setPosts(current=>[saved,...current]);setDraft('');setNotice('Your argument has been added to the thread.');}catch(error){setNotice(error?.message||'Post could not be saved.');}}return <div className="match-forum-modal" role="presentation" onMouseDown={onClose}><section className="match-forum-modal__dialog" onMouseDown={e=>e.stopPropagation()}><button className="match-forum-modal__close" type="button" onClick={onClose}><X size={18}/></button><div className="match-forum-modal__kicker"><MessageSquare size={14}/> Debate forum</div><h3>{title}</h3><p>The thread stays attached to this exact debate.</p>{user?<><div className="match-forum-composer"><textarea rows="3" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Make the football argument…"/><button className="btn btn--lime btn--sm" type="button" onClick={post}><Send size={13}/> POST</button></div>{notice&&<small>{notice}</small>}<div className="match-forum-posts">{posts.length?posts.map((p,i)=><article key={`${p.created_at}-${i}`}><b>{p.author_email||'Calibre user'}</b><p>{p.body}</p><small>{p.created_at?new Date(p.created_at).toLocaleString():'now'}</small></article>):<div className="comp-empty-state">Start the discussion.</div>}</div></>:<div className="match-forum-locked"><LockKeyhole size={20}/><div><b>Verified account required</b><span>Log in or create an account before posting.</span></div><button className="btn btn--lime btn--sm" type="button" onClick={()=>requestAuth(`/debates?forum=${slug}`)}>LOG IN OR CREATE ACCOUNT</button></div>}</section></div>}
function NominateModal({onClose}){const{user}=useAuth();const[title,setTitle]=useState('');const[reason,setReason]=useState('');const[notice,setNotice]=useState('');async function submit(e){e.preventDefault();if(!user)return requestAuth('/debates');try{const result=await submitDebateNomination({title,reason,userId:user.id,email:user.email});setNotice(result.source==='supabase'?'Nomination submitted for editorial review.':'Nomination stored in beta mode. Connect Supabase to make it persistent.');setTitle('');setReason('');}catch(error){setNotice(error?.message||'Nomination failed.');}}return <div className="match-forum-modal" role="presentation" onMouseDown={onClose}><section className="match-forum-modal__dialog" onMouseDown={e=>e.stopPropagation()}><button className="match-forum-modal__close" type="button" onClick={onClose}><X size={18}/></button><div className="match-forum-modal__kicker"><Star size={14}/> Nominate a debate</div><h3>Put the next football argument on the board.</h3><form className="debate-nominate-form" onSubmit={submit}><input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Debate question"/><textarea value={reason} onChange={e=>setReason(e.target.value)} rows="4" required placeholder="Why will this argument move the conversation?"/><button className="btn btn--lime" type="submit">SUBMIT NOMINATION</button></form>{notice&&<small>{notice}</small>}</section></div>}

export default function Debates(){
  const{user}=useAuth(); const[feed,setFeed]=useState([]);const[hot,setHot]=useState([]);const[tweets,setTweets]=useState([]);const[source,setSource]=useState('loading');const[nominate,setNominate]=useState(false);const[forum,setForum]=useState(null);const[goat,setGoat]=useState(()=>{try{return localStorage.getItem('calibre:goat-vote:device')||''}catch{return''}});const[goatNotice,setGoatNotice]=useState('');
  useEffect(()=>{Promise.all([loadDebateFeed(),loadHotPotatoes(),loadBangerTweets()]).then(([d,h,t])=>{setFeed(d.rows);setHot(h.rows);setTweets(t.rows);setSource(d.source);});},[]);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const slug=params.get('forum');const topic=params.get('topic');if(slug)setForum({slug,title:feed.find(d=>d.slug===slug)?.title||slug.replaceAll('-',' ')});else if(topic)setForum({slug:`topic-${topic.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,title:topic});},[feed]);
  const trending=useMemo(()=>[...feed].sort((a,b)=>(b.votes||0)-(a.votes||0)).slice(0,6),[feed]);
  async function voteGoat(choice){try{await castGoatVote(choice,user);setGoat(choice);setGoatNotice(`Vote locked: ${choice}.`);}catch(error){setGoatNotice(error?.message||'Vote could not be recorded.');}}
  return <div className="page debates-page"><div className="debates-header"><div><span>DEBATES</span><h1>Rate Battles</h1><p>Vote on today’s matchups, enter fixture forums and nominate the arguments football is about to have.</p></div><button className="btn btn--lime" type="button" onClick={()=>setNominate(true)}>NOMINATE A DEBATE</button></div><div className="debate-source-note"><i/> {source==='supabase'?'LIVE COMMUNITY FEED':'EDITORIAL SNAPSHOT · CONNECT SUPABASE FOR PERSISTENT COMMUNITY CONTENT'}</div>
  <div className="debate-layout"><main className="debate-main"><section><div className="section-title-row"><div><span className="section-kicker"><Zap size={13}/> Active rate battles</span><h2>Arguments moving now.</h2></div></div><div className="battle-grid">{feed.filter(d=>d.category==='rate-battle').slice(0,4).map(item=>{const pair=BATTLE_VISUALS[item.slug]||[item.left||'Pedri',item.right||'Jude Bellingham'];return <button className="battle-preview" type="button" key={item.slug} onClick={()=>setForum(item)}><div className="battle-preview__header"><span className="battle-preview__live"><i/>Live</span><span>{(item.votes||0).toLocaleString()} votes</span></div><div className="battle-preview__players"><div><ApiPlayerImage apiPlayerId={playerIdFor(pair[0])} name={pair[0]} fallbackSrc="/assets/players/neutral-player.svg"/><strong>{pair[0]}</strong></div><span>vs</span><div><ApiPlayerImage apiPlayerId={playerIdFor(pair[1])} name={pair[1]} fallbackSrc="/assets/players/neutral-player.svg"/><strong>{pair[1]}</strong></div></div><p>{item.title}</p></button>})}</div></section>
  <section className="debate-section"><div className="section-title-row"><div><span className="section-kicker"><Flame size={13}/> Hot potatoes</span><h2>Arguments that need a proper thread.</h2></div></div><div className="hot-potato-grid">{hot.map(item=><button className="panel hot-potato-card" type="button" key={item.slug} onClick={()=>setForum(item)}><span>HOT POTATO</span><h3>{item.title}</h3><p>{item.context}</p><b>YES {item.yes}% · NO {100-item.yes}%</b></button>)}</div></section>
  <section className="debate-section"><div className="section-title-row"><div><span className="section-kicker"><MessageSquare size={13}/> Banger tweets</span><h2>Editorial picks from the football timeline.</h2></div></div><div className="banger-grid">{tweets.map((item,i)=><article className="panel banger-card" key={`${item.handle}-${i}`}><b>{item.handle}</b><p>“{item.text}”</p><small>♥ {item.likes} · ↻ {item.reposts||item.rt}</small></article>)}</div></section>
  <section className="panel goat-panel"><span className="section-kicker">🐐 GOAT DEBATE</span><h2>Messi or Ronaldo?</h2><div className="goat-grid"><button type="button" className={goat==='Messi'?'is-voted':''} onClick={()=>voteGoat('Messi')}><ApiPlayerImage apiPlayerId={playerIdFor('Lionel Messi')} name="Lionel Messi" fallbackSrc="/assets/players/neutral-player.svg"/><strong>Messi</strong></button><span>VS</span><button type="button" className={goat==='Ronaldo'?'is-voted':''} onClick={()=>voteGoat('Ronaldo')}><ApiPlayerImage apiPlayerId={playerIdFor('Cristiano Ronaldo')} name="Cristiano Ronaldo" fallbackSrc="/assets/players/neutral-player.svg"/><strong>Ronaldo</strong></button></div>{goatNotice&&<p>{goatNotice}</p>}</section></main><aside className="debate-rail"><div className="panel"><div className="panel-head"><div className="panel-title"><TrendingUp size={12}/> Trending this week</div></div>{trending.map((item,index)=><button className="trending-debate-row" type="button" key={item.slug} onClick={()=>setForum(item)}><i>{index+1}</i><span><b>{item.title}</b><small>{(item.votes||0).toLocaleString()} votes · {item.comments||0} comments</small></span><ArrowRight size={13}/></button>)}</div><div className="panel debate-account-card"><Users size={18}/><h3>{user?'Account connected':'Join the forums'}</h3><p>{user?`Posting as ${user.email}`:'A verified account is required to post and nominate debates.'}</p>{!user&&<button className="btn btn--lime btn--sm" type="button" onClick={()=>requestAuth('/debates')}>CREATE ACCOUNT</button>}</div></aside></div><div className="founder-strip"><Crown size={20}/><strong>Get World Cup Founder Pass</strong><span>Unlock premium debates, advanced filters and exclusive World Cup intelligence.</span><button className="btn btn--lime" type="button" onClick={()=>navigateTo('/pricing')}>EXPLORE PLANS <ArrowRight size={13}/></button></div>{nominate&&<NominateModal onClose={()=>setNominate(false)}/>} {forum&&<ForumModal slug={forum.slug} title={forum.title} onClose={()=>setForum(null)}/>}</div>;
}
