import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Crown, Flame, LockKeyhole, MessageSquare, Send, Star, TrendingUp, Users, X, Zap } from 'lucide-react';
import { navigateTo } from '../components/NavLink.jsx';
import ApiPlayerImage from '../components/ApiPlayerImage.jsx';
import { playerIdFor } from '../data/playerIds.js';
import ShareBar, { shareUrl } from '../components/Share.jsx';
import useAuth from '../hooks/useAuth.js';
import { castGoatVote, castBattleVote, loadDebateVoteCounts, myBattleVote, loadGoatVoteCounts, loadBangerTweets, loadDebateFeed, loadForumPosts, loadHotPotatoes, submitDebateNomination, submitForumPost } from '../services/community.js';

const BATTLE_VISUALS={
  'pedri-vs-jude':['Pedri','Jude Bellingham'], 'mbappe-vs-haaland':['Kylian Mbappé','Erling Haaland'], 'vini-vs-saka':['Vinícius Júnior','Bukayo Saka'],
};
function requestAuth(returnTo='/debates'){window.dispatchEvent(new CustomEvent('calibre:open-auth',{detail:{returnTo}}));}
function ForumModal({slug,title,onClose}){const{user,displayName}=useAuth();const[draft,setDraft]=useState('');const[posts,setPosts]=useState([]);const[notice,setNotice]=useState('');useEffect(()=>{loadForumPosts(slug).then(setPosts).catch(()=>setPosts([]));},[slug]);async function post(){if(!user)return requestAuth(`/debates?forum=${slug}`);const body=draft.trim();if(!body)return;try{const saved=await submitForumPost({threadSlug:slug,body,user,username:displayName});setPosts(current=>[saved,...current]);setDraft('');setNotice('Your argument has been added to the thread.');}catch(error){setNotice(error?.message||'Post could not be saved.');}}return <div className="match-forum-modal" role="presentation" onMouseDown={onClose}><section className="match-forum-modal__dialog" onMouseDown={e=>e.stopPropagation()}><button className="match-forum-modal__close" type="button" onClick={onClose}><X size={18}/></button><div className="match-forum-modal__kicker"><MessageSquare size={14}/> Debate forum</div><h3>{title}</h3><p>The thread stays attached to this exact debate.</p>{user?<><div className="match-forum-composer"><textarea rows="3" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Make the football argument…"/><button className="btn btn--lime btn--sm" type="button" onClick={post}><Send size={13}/> POST</button></div>{notice&&<small>{notice}</small>}<div className="match-forum-posts">{posts.length?posts.map((p,i)=><article key={`${p.created_at}-${i}`}><b>{p.author_name||p.author_email||'Calibre user'}</b><p>{p.body}</p><small>{p.created_at?new Date(p.created_at).toLocaleString():'now'}</small></article>):<div className="comp-empty-state">Start the discussion.</div>}</div></>:<div className="match-forum-locked"><LockKeyhole size={20}/><div><b>Verified account required</b><span>Log in or create an account before posting.</span></div><button className="btn btn--lime btn--sm" type="button" onClick={()=>requestAuth(`/debates?forum=${slug}`)}>LOG IN OR CREATE ACCOUNT</button></div>}</section></div>}
function NominateModal({onClose}){const{user}=useAuth();const[title,setTitle]=useState('');const[reason,setReason]=useState('');const[notice,setNotice]=useState('');async function submit(e){e.preventDefault();if(!user)return requestAuth('/debates');try{const result=await submitDebateNomination({title,reason,userId:user.id,email:user.email});setNotice(result.source==='supabase'?'Nomination submitted for editorial review.':'Nomination stored in beta mode. Connect Supabase to make it persistent.');setTitle('');setReason('');}catch(error){setNotice(error?.message||'Nomination failed.');}}return <div className="match-forum-modal" role="presentation" onMouseDown={onClose}><section className="match-forum-modal__dialog" onMouseDown={e=>e.stopPropagation()}><button className="match-forum-modal__close" type="button" onClick={onClose}><X size={18}/></button><div className="match-forum-modal__kicker"><Star size={14}/> Nominate a debate</div><h3>Put the next football argument on the board.</h3><form className="debate-nominate-form" onSubmit={submit}><input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Debate question"/><textarea value={reason} onChange={e=>setReason(e.target.value)} rows="4" required placeholder="Why will this argument move the conversation?"/><button className="btn btn--lime" type="submit">SUBMIT NOMINATION</button></form>{notice&&<small>{notice}</small>}</section></div>}

export default function Debates(){
  const{user,displayName}=useAuth(); const[feed,setFeed]=useState([]);const[hot,setHot]=useState([]);const[tweets,setTweets]=useState([]);const[source,setSource]=useState('loading');const[nominate,setNominate]=useState(false);const[forum,setForum]=useState(null);const[goat,setGoat]=useState(()=>{try{return localStorage.getItem('calibre:goat-vote:device')||''}catch{return''}});const[goatNotice,setGoatNotice]=useState('');const[voteCounts,setVoteCounts]=useState({});const[myVotes,setMyVotes]=useState({});const[goatCounts,setGoatCounts]=useState({Messi:0,Ronaldo:0,total:0});
  useEffect(()=>{Promise.all([loadDebateFeed(),loadHotPotatoes(),loadBangerTweets()]).then(([d,h,t])=>{setFeed(d.rows);setHot(h.rows);setTweets(t.rows);setSource(d.source);});},[]);
  // Load live vote counts, and read this device's existing votes from local.
  useEffect(()=>{loadDebateVoteCounts().then(setVoteCounts).catch(()=>{});},[]);
  useEffect(()=>{loadGoatVoteCounts().then(setGoatCounts).catch(()=>{});},[]);
  useEffect(()=>{const mine={};for(const d of feed){if(d.category==='rate-battle'){const v=myBattleVote(d.slug);if(v)mine[d.slug]=v;}}setMyVotes(mine);},[feed]);
  async function voteBattle(slug,choice){try{await castBattleVote(slug,choice,user);setMyVotes(m=>({...m,[slug]:choice}));setVoteCounts(c=>{const cur=c[slug]||{left:0,right:0};return{...c,[slug]:{...cur,[choice]:(cur[choice]||0)+1}};});}catch(_){/* already voted or offline — keep UI as is */setMyVotes(m=>({...m,[slug]:myBattleVote(slug)||m[slug]}));}}
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const slug=params.get('forum');const topic=params.get('topic');if(slug)setForum({slug,title:feed.find(d=>d.slug===slug)?.title||slug.replaceAll('-',' ')});else if(topic)setForum({slug:`topic-${topic.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,title:topic});},[feed]);
  const trending=useMemo(()=>[...feed].sort((a,b)=>(b.votes||0)-(a.votes||0)).slice(0,6),[feed]);
  async function voteGoat(choice){try{await castGoatVote(choice,user);setGoat(choice);setGoatCounts(c=>({...c,[choice]:(c[choice]||0)+1,total:(c.total||0)+1}));setGoatNotice('');}catch(error){setGoatNotice(error?.message||'Vote could not be recorded.');}}
  return <div className="page debates-page"><div className="debates-header"><div><span>DEBATES</span><h1>Rate Battles</h1><p>Vote on today’s matchups, enter fixture forums and nominate the arguments football is about to have.</p></div><button className="btn btn--lime" type="button" onClick={()=>setNominate(true)}>NOMINATE A DEBATE</button></div><div className="debate-source-note"><i/> {source==='supabase'?'LIVE COMMUNITY FEED':'EDITORIAL SNAPSHOT · CONNECT SUPABASE FOR PERSISTENT COMMUNITY CONTENT'}</div>
  <div className="debate-layout"><main className="debate-main"><section><div className="section-title-row"><div><span className="section-kicker"><Zap size={13}/> Active rate battles</span><h2>Arguments moving now.</h2></div></div><div className="battle-grid">{feed.filter(d=>d.category==='rate-battle').slice(0,4).map(item=>{const pair=BATTLE_VISUALS[item.slug]||[item.left||'Pedri',item.right||'Jude Bellingham'];const base=item.votes||0;const live=voteCounts[item.slug]||{left:0,right:0};const l=Math.round(base*0.5)+live.left;const r=(base-Math.round(base*0.5))+live.right;const total=l+r||1;const lpct=Math.round(l/total*100);const mine=myVotes[item.slug];const totalVotes=base+live.left+live.right;return <div className="battle-preview" key={item.slug}><div className="battle-preview__header"><span className="battle-preview__live"><i/>Live</span><span>{totalVotes.toLocaleString()} votes</span></div><div className="battle-preview__players"><button type="button" className={`battle-player${mine==='left'?' is-voted':''}`} onClick={()=>voteBattle(item.slug,'left')} title={mine?'You voted':'Vote'+' '+pair[0]}><ApiPlayerImage playerId={playerIdFor(pair[0])} name={pair[0]} fallbackSrc="/assets/players/neutral-player.svg"/><strong>{pair[0]}</strong>{mine&&<em className="battle-pct">{lpct}%</em>}</button><span className="battle-vs">vs</span><button type="button" className={`battle-player${mine==='right'?' is-voted':''}`} onClick={()=>voteBattle(item.slug,'right')} title={mine?'You voted':'Vote'+' '+pair[1]}><ApiPlayerImage playerId={playerIdFor(pair[1])} name={pair[1]} fallbackSrc="/assets/players/neutral-player.svg"/><strong>{pair[1]}</strong>{mine&&<em className="battle-pct">{100-lpct}%</em>}</button></div><button type="button" className="battle-preview__title" onClick={()=>setForum(item)}>{item.title}</button><div className="battle-preview__share"><ShareBar text={`${item.title} — ${pair[0]} vs ${pair[1]}. Settle it on Calibre.`} url={shareUrl('/debates')} label={false}/></div></div>})}</div></section>
  <section className="debate-section"><div className="section-title-row"><div><span className="section-kicker"><Flame size={13}/> Hot potatoes</span><h2>Arguments that need a proper thread.</h2></div></div><div className="hot-potato-grid">{hot.map(item=>{const live=voteCounts[item.slug]||{left:0,right:0};const base=100;const y=Math.round(item.yes*base/100)+live.left;const n=(base-Math.round(item.yes*base/100))+live.right;const tot=y+n||1;const ypct=Math.round(y/tot*100);const mine=myVotes[item.slug];return <div className="panel hot-potato-card" key={item.slug}><button className="hot-potato-card__open" type="button" onClick={()=>setForum(item)}><span>HOT POTATO</span><h3>{item.title}</h3><p>{item.context}</p></button><div className="hot-potato-vote">{mine?<b className="hot-potato-result">YES {ypct}% · NO {100-ypct}%</b>:<><button type="button" className="hp-vote" onClick={()=>voteBattle(item.slug,'left')}>YES</button><button type="button" className="hp-vote" onClick={()=>voteBattle(item.slug,'right')}>NO</button></>}</div><div className="hot-potato-card__share"><ShareBar text={`${item.title} — ${ypct}% say YES on Calibre.`} url={shareUrl('/debates')} label={false}/></div></div>})}</div></section>
  <section className="debate-section"><div className="section-title-row"><div><span className="section-kicker"><MessageSquare size={13}/> Banger tweets</span><h2>Editorial picks from the football timeline.</h2></div></div><div className="banger-grid">{tweets.map((item,i)=><article className="panel banger-card" key={`${item.handle}-${i}`}><b>{item.handle}</b><p>“{item.text}”</p><small>♥ {item.likes} · ↻ {item.reposts||item.rt}</small></article>)}</div></section>
  <section className="panel goat-panel"><span className="section-kicker">🐐 GOAT DEBATE</span><h2>Messi or Ronaldo?</h2>{(()=>{const gt=goatCounts.total||0;const mpct=gt?Math.round(goatCounts.Messi/gt*100):50;return <><div className="goat-count">{gt.toLocaleString()} votes</div><div className="goat-grid"><button type="button" className={`battle-player${goat==='Messi'?' is-voted':''}`} onClick={()=>voteGoat('Messi')}><ApiPlayerImage playerId={playerIdFor('Lionel Messi')} name="Lionel Messi" fallbackSrc="/assets/players/neutral-player.svg"/><strong>Messi</strong>{goat&&<em className="battle-pct">{mpct}%</em>}</button><span className="battle-vs">VS</span><button type="button" className={`battle-player${goat==='Ronaldo'?' is-voted':''}`} onClick={()=>voteGoat('Ronaldo')}><ApiPlayerImage playerId={playerIdFor('Cristiano Ronaldo')} name="Cristiano Ronaldo" fallbackSrc="/assets/players/neutral-player.svg"/><strong>Ronaldo</strong>{goat&&<em className="battle-pct">{100-mpct}%</em>}</button></div></>;})()}{goatNotice&&<p>{goatNotice}</p>}<div className="goat-share"><ShareBar text={`Messi or Ronaldo? Cast your GOAT vote on Calibre.`} url={shareUrl('/debates')}/></div></section></main><aside className="debate-rail"><div className="panel"><div className="panel-head"><div className="panel-title"><TrendingUp size={12}/> Trending this week</div></div>{trending.map((item,index)=><button className="trending-debate-row" type="button" key={item.slug} onClick={()=>setForum(item)}><i>{index+1}</i><span><b>{item.title}</b><small>{(item.votes||0).toLocaleString()} votes · {item.comments||0} comments</small></span><ArrowRight size={13}/></button>)}</div><div className="panel debate-account-card"><Users size={18}/><h3>{user?'Account connected':'Join the forums'}</h3><p>{user?`Posting as ${displayName}`:'A verified account is required to post and nominate debates.'}</p>{!user&&<button className="btn btn--lime btn--sm" type="button" onClick={()=>requestAuth('/debates')}>CREATE ACCOUNT</button>}</div></aside></div><div className="founder-strip"><Crown size={20}/><strong>Get World Cup Founder Pass</strong><span>Unlock premium debates, advanced filters and exclusive World Cup intelligence.</span><button className="btn btn--lime" type="button" onClick={()=>navigateTo('/pricing')}>EXPLORE PLANS <ArrowRight size={13}/></button></div>{nominate&&<NominateModal onClose={()=>setNominate(false)}/>} {forum&&<ForumModal slug={forum.slug} title={forum.title} onClose={()=>setForum(null)}/>}</div>;
}
